//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bodega_Detalle
    {
        public int id_Bodega_Detalle { get; set; }
        public int id_bodega_productos { get; set; }
        public int id_talla { get; set; }
        public int id_color { get; set; }
        public int cantidad { get; set; }
    
        public virtual Tbl_bodega_productos Tbl_bodega_productos { get; set; }
        public virtual Tbl_Color Tbl_Color { get; set; }
        public virtual Tbl_Talla Tbl_Talla { get; set; }
    }
}
