//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidaDetalle
    {
        public int idSalidaDetalle { get; set; }
        public int Id_Salida { get; set; }
        public int id_articulo { get; set; }
        public string descripcion { get; set; }
        public int cantidad { get; set; }
        public int id_Kardex { get; set; }
    
        public virtual Tbl_Articulo Tbl_Articulo { get; set; }
        public virtual Tbl_Kardex Tbl_Kardex { get; set; }
        public virtual Tbl_Salida Tbl_Salida { get; set; }
    }
}
