//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidaDetalle
    {
        public int idSalidaDetalle { get; set; }
        public int Id_Salida { get; set; }
        public int id_articulo { get; set; }
        public string descripcion { get; set; }
        public int cantidad { get; set; }
        public int id_Kardex { get; set; }
    
        public virtual Tbl_Articulo Tbl_Articulo { get; set; }
        public virtual Tbl_Kardex Tbl_Kardex { get; set; }
        public virtual Tbl_Salida Tbl_Salida { get; set; }
    }
}
