//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Configuracion
    {
        public int id_Configuracion { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<int> id_sucursal { get; set; }
    
        public virtual Tbl_Sucursal Tbl_Sucursal { get; set; }
    }
}
