//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DevolucionCliente
    {
        public int id_devolucionCliente { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_venta { get; set; }
    
        public virtual Tbl_Orden Tbl_Orden { get; set; }
    }
}
