//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Pago_Apartado
    {
        public int id_pago_apartado { get; set; }
        public int id_apartado { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public double Cantidad { get; set; }
        public double saldo { get; set; }
    
        public virtual Tbl_Apartado Tbl_Apartado { get; set; }
    }
}
