//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kardex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Kardex()
        {
            this.SalidaDetalle = new HashSet<SalidaDetalle>();
            this.Tbl_Detalle_Compra = new HashSet<Tbl_Detalle_Compra>();
            this.Tbl_Detalle_Orden = new HashSet<Tbl_Detalle_Orden>();
        }
    
        public int id_Kardex { get; set; }
        public int id_articulo { get; set; }
        public System.DateTime fechaKardex { get; set; }
        public string num_factura { get; set; }
        public int Entrada { get; set; }
        public int salida { get; set; }
        public int saldo { get; set; }
        public double precio { get; set; }
        public double costoPromedio { get; set; }
        public string usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalidaDetalle> SalidaDetalle { get; set; }
        public virtual Tbl_Articulo Tbl_Articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Detalle_Compra> Tbl_Detalle_Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Detalle_Orden> Tbl_Detalle_Orden { get; set; }
    }
}
