//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_bodega_productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_bodega_productos()
        {
            this.Bodega_Detalle = new HashSet<Bodega_Detalle>();
        }
    
        public int id_bodega_productos { get; set; }
        public int id_sucursal { get; set; }
        public int id_articulo { get; set; }
        public int stock { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<double> preciocredito { get; set; }
        public Nullable<bool> credito { get; set; }
        public Nullable<bool> apartado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bodega_Detalle> Bodega_Detalle { get; set; }
        public virtual Tbl_Articulo Tbl_Articulo { get; set; }
        public virtual Tbl_Sucursal Tbl_Sucursal { get; set; }
    }
}
