//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Articulo()
        {
            this.SalidaDetalle = new HashSet<SalidaDetalle>();
            this.Tbl_bodega_productos = new HashSet<Tbl_bodega_productos>();
            this.Tbl_CompraTmp = new HashSet<Tbl_CompraTmp>();
            this.Tbl_DescripcionValores = new HashSet<Tbl_DescripcionValores>();
            this.Tbl_Detalle_Compra = new HashSet<Tbl_Detalle_Compra>();
            this.Tbl_Detalle_Orden = new HashSet<Tbl_Detalle_Orden>();
            this.Tbl_DetalleDevolucionCliente = new HashSet<Tbl_DetalleDevolucionCliente>();
            this.Tbl_DetalleDevolucionProveedor = new HashSet<Tbl_DetalleDevolucionProveedor>();
            this.Tbl_DevolucionDetalleTmp = new HashSet<Tbl_DevolucionDetalleTmp>();
            this.Tbl_Kardex = new HashSet<Tbl_Kardex>();
            this.Tbl_OrdenTmp = new HashSet<Tbl_OrdenTmp>();
        }
    
        public int id_articulo { get; set; }
        public string codigo_articulo { get; set; }
        public string nombre_articulo { get; set; }
        public string descripcion_articulo { get; set; }
        public int id_categoria { get; set; }
        public int credito_articulo { get; set; }
        public int id_Marca { get; set; }
        public int GarantiaCant { get; set; }
        public Nullable<bool> estado { get; set; }
        public string imagen { get; set; }
        public string GarantiaMedida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalidaDetalle> SalidaDetalle { get; set; }
        public virtual Tbl_Categorias Tbl_Categorias { get; set; }
        public virtual Tbl_Marca Tbl_Marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_bodega_productos> Tbl_bodega_productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_CompraTmp> Tbl_CompraTmp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_DescripcionValores> Tbl_DescripcionValores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Detalle_Compra> Tbl_Detalle_Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Detalle_Orden> Tbl_Detalle_Orden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_DetalleDevolucionCliente> Tbl_DetalleDevolucionCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_DetalleDevolucionProveedor> Tbl_DetalleDevolucionProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_DevolucionDetalleTmp> Tbl_DevolucionDetalleTmp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Kardex> Tbl_Kardex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrdenTmp> Tbl_OrdenTmp { get; set; }
    }
}
