//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Compra
    {
        public int id_compra { get; set; }
        public int id_proveedor { get; set; }
        public System.DateTime fecha_compra { get; set; }
        public string fact_compra { get; set; }
        public string tipo_comprobante_compra { get; set; }
        public decimal iva_compra { get; set; }
        public string usuario { get; set; }
        public int id_bodega { get; set; }
    
        public virtual Tbl_bodega Tbl_bodega { get; set; }
        public virtual Tbl_Proveedor Tbl_Proveedor { get; set; }
    }
}
