//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Descripciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Descripciones()
        {
            this.Tbl_DescripcionValores = new HashSet<Tbl_DescripcionValores>();
        }
    
        public int id_descripcion { get; set; }
        public int id_categoria { get; set; }
        public string nombre { get; set; }
    
        public virtual Tbl_Categorias Tbl_Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_DescripcionValores> Tbl_DescripcionValores { get; set; }
    }
}
