//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ProveedorTmp
    {
        public int id_proveedorTmp { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string ruc { get; set; }
        public bool nuevo { get; set; }
        public string user { get; set; }
        public Nullable<int> id_proveedor { get; set; }
    }
}
