//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Salida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Salida()
        {
            this.SalidaDetalle = new HashSet<SalidaDetalle>();
        }
    
        public int IDSalida { get; set; }
        public System.DateTime fecha { get; set; }
        public int IdConcepto { get; set; }
        public int IdSucursal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalidaDetalle> SalidaDetalle { get; set; }
        public virtual Tbl_Concepto Tbl_Concepto { get; set; }
        public virtual Tbl_Sucursal Tbl_Sucursal { get; set; }
    }
}
