//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Pago_Credito
    {
        public int id_pago_credito { get; set; }
        public int id_credito { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public double cantidad { get; set; }
        public Nullable<double> mora { get; set; }
        public double saldo { get; set; }
        public Nullable<System.DateTime> fecha_estimada_pago { get; set; }
    
        public virtual Tbl_Credito Tbl_Credito { get; set; }
    }
}
