//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Apartado
    {
        public int id_apartado { get; set; }
        public System.DateTime fecha_plazo { get; set; }
        public double importe { get; set; }
        public int id_orden { get; set; }
        public int id_cliente { get; set; }
    
        public virtual Tbl_Clientes Tbl_Clientes { get; set; }
        public virtual Tbl_Orden Tbl_Orden { get; set; }
        public virtual Tbl_Pago_Apartado Tbl_Pago_Apartado { get; set; }
    }
}
