//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Orden()
        {
            this.Tbl_Apartado = new HashSet<Tbl_Apartado>();
            this.Tbl_Credito = new HashSet<Tbl_Credito>();
            this.Tbl_Detalle_Orden = new HashSet<Tbl_Detalle_Orden>();
        }
    
        public int id_orden { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha_orden { get; set; }
        public decimal iva_orden { get; set; }
        public string estado_orden { get; set; }
        public string tipo_orden { get; set; }
        public string fact_Orden { get; set; }
        public int id_bodega { get; set; }
        public string NombreCliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Apartado> Tbl_Apartado { get; set; }
        public virtual Tbl_bodega Tbl_bodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Credito> Tbl_Credito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Detalle_Orden> Tbl_Detalle_Orden { get; set; }
        public virtual Tbl_Sucursal Tbl_Sucursal { get; set; }
    }
}
