//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Pago_Apartado
    {
        public int id_pago_apartado { get; set; }
        public int id_apartado { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public double Cantidad { get; set; }
        public double saldo { get; set; }
    
        public virtual Tbl_Apartado Tbl_Apartado { get; set; }
    }
}
