//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DevolucionDetalleTmp
    {
        public int id_detalleDevolucion { get; set; }
        public int id_articulo { get; set; }
        public string descripcion { get; set; }
        public int cantidad { get; set; }
        public string user { get; set; }
        public string tipo { get; set; }
        public Nullable<int> cantidadcomprada { get; set; }
    
        public virtual Tbl_Articulo Tbl_Articulo { get; set; }
    }
}
