//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DevolucionTmp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_DevolucionTmp()
        {
            this.Tbl_DevolucionDetalleTmp = new HashSet<Tbl_DevolucionDetalleTmp>();
        }
    
        public int id_devolucion { get; set; }
        public string tipo { get; set; }
        public Nullable<int> iva { get; set; }
        public int id_transaccion { get; set; }
        public string user { get; set; }
    
        public virtual Tbl_Compra Tbl_Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_DevolucionDetalleTmp> Tbl_DevolucionDetalleTmp { get; set; }
        public virtual Tbl_Orden Tbl_Orden { get; set; }
    }
}
