//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Devolucion
    {
        public double id_devolucion { get; set; }
        public System.DateTime fecha_devolucion { get; set; }
        public string usuario { get; set; }
        public int id_garantia { get; set; }
        public int id_orden { get; set; }
        public int id_kardex { get; set; }
    
        public virtual Tbl_garantia Tbl_garantia { get; set; }
    }
}
