//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Detalle_Orden
    {
        public int id_detalle_orden { get; set; }
        public int id_articulo { get; set; }
        public int id_orden { get; set; }
        public int cantidad { get; set; }
        public double precio_venta { get; set; }
        public Nullable<double> descuento { get; set; }
        public int id_kardex { get; set; }
        public string motivo { get; set; }
    
        public virtual Tbl_Articulo Tbl_Articulo { get; set; }
        public virtual Tbl_Kardex Tbl_Kardex { get; set; }
        public virtual Tbl_Orden Tbl_Orden { get; set; }
    }
}
