//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DevolucionProveedor
    {
        public int id_DevolucionProveedor { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_compra { get; set; }
    
        public virtual Tbl_Compra Tbl_Compra { get; set; }
    }
}
