//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Pago_Credito
    {
        public int id_pago_credito { get; set; }
        public int id_credito { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public double cantidad { get; set; }
        public Nullable<double> mora { get; set; }
        public double saldo { get; set; }
        public Nullable<System.DateTime> fecha_estimada_pago { get; set; }
    
        public virtual Tbl_Credito Tbl_Credito { get; set; }
    }
}
