//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Descripciones
    {
        public int id_descripcion { get; set; }
        public int id_categoria { get; set; }
        public string nombre { get; set; }
    
        public virtual Tbl_Categorias Tbl_Categorias { get; set; }
        public virtual Tbl_DescripcionValores Tbl_DescripcionValores { get; set; }
    }
}
