//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DetalleDevolucionProveedor
    {
        public int id_detalleDevolucionPro { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> id_kardex { get; set; }
    
        public virtual Tbl_Articulo Tbl_Articulo { get; set; }
        public virtual Tbl_DevolucionProveedor Tbl_DevolucionProveedor { get; set; }
        public virtual Tbl_Kardex Tbl_Kardex { get; set; }
    }
}
