//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Credito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Credito()
        {
            this.Tbl_Pago_Credito = new HashSet<Tbl_Pago_Credito>();
        }
    
        public int id_credito { get; set; }
        public int id_orden { get; set; }
        public int meses_plazo { get; set; }
        public double importe { get; set; }
        public double amortizacion { get; set; }
        public System.DateTime fecha_consolidacion { get; set; }
        public int cuotas { get; set; }
        public Nullable<double> interesPorMora { get; set; }
        public int id_cliente { get; set; }
    
        public virtual Tbl_Clientes Tbl_Clientes { get; set; }
        public virtual Tbl_Orden Tbl_Orden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Pago_Credito> Tbl_Pago_Credito { get; set; }
    }
}
