//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmilcarComercial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_garantia
    {
        public int id_garantia { get; set; }
        public string cod_garantia { get; set; }
        public string plazo_garantia { get; set; }
        public string estado { get; set; }
        public int id_detalle_orden { get; set; }
    }
}
